import PDFDocument from 'pdfkit';

export default async function handler(req, res) {
  if (req.method === 'POST') {
    return handlePostRequest(req, res);
  } else if (req.method === 'GET') {
    // Redirect GET to a basic error or handle similarly
    return res.status(405).json({ error: 'Please use POST for PDF generation' });
  } else {
    return res.status(405).json({ error: 'Method not allowed' });
  }
}

async function handlePostRequest(req, res) {
  try {
    const { title, grade, subject, docType, questions, answerKey, includeAnswerKey } = req.body;

    if (!questions || !Array.isArray(questions)) {
      return res.status(400).json({ error: 'Questions array required' });
    }

    // 1. Create PDF document
    const doc = new PDFDocument({
      bufferPages: true,
      size: 'A4',
      margin: 50,
    });

    // 2. Set response headers
    const filename = (title || 'document').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`);

    // 3. Pipe to response
    doc.pipe(res);

    // --- PDF CONTENT GENERATION ---

    // Title
    doc.fillColor('#111827').fontSize(24).font('Helvetica-Bold').text(title || 'Document', { align: 'center' });
    doc.moveDown(0.5);

    // Metadata Bar
    doc.fontSize(10).font('Helvetica').fillColor('#6b7280');
    const metadata = `Grade: ${grade} | Subject: ${subject} | Type: ${docType}`;
    doc.text(metadata, { align: 'center' });
    doc.moveDown(1.5);

    // Divider
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(2);

    // Questions section
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('Questions');
    doc.moveDown(1);

    questions.forEach((question, index) => {
      const questionText = sanitizeText(question);
      
      // Question number
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#4f46e5').text(`${index + 1}. `, { continued: true });

      // Question body
      doc.font('Helvetica').fillColor('#374151').text(questionText);
      doc.moveDown(2); // Space for student to write
    });

    // Answer key section
    if (includeAnswerKey && answerKey && answerKey.length > 0) {
      doc.addPage();
      doc.fontSize(18).font('Helvetica-Bold').fillColor('#111827').text('Answer Key');
      doc.moveDown(1.5);

      answerKey.forEach((answer, index) => {
        const answerText = typeof answer === 'object' ? answer.text : answer;
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#10b981').text(`A${index + 1}: `, { continued: true });
        doc.font('Helvetica').fillColor('#374151').text(sanitizeText(answerText));
        doc.moveDown(1);
      });
    }

    // 4. Add Footers (Page Numbers)
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor('#9ca3af').text(
        `Page ${i + 1} of ${range.count} | ${title} | Generated by AI Educator`,
        50,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width - 100 }
      );
    }

    // 5. Finalize and wait for stream
    doc.end();

  } catch (error) {
    console.error('PDF generation error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF', details: error.message });
    }
  }
}

function sanitizeText(text) {
  if (!text) return '';
  // PDFKit's default fonts don't handle some Unicode well. 
  // This helps prevent crashes on special characters.
  return String(text)
    .replace(/[\u2018\u2019]/g, "'") // Smart quotes to straight
    .replace(/[\u201C\u201D]/g, '"') // Smart double quotes
    .replace(/[\u2013\u2014]/g, '-') // Em/En dashes
    .trim();
}
